from __future__ import annotations

# Import all models so Alembic can discover metadata
from app.models.audit import AuditLog
from app.models.company_setup import (
    ApprovalStep,
    ApprovalWorkflow,
    Branch,
    CompanyProfile,
    CostCenter,
    Department,
    Designation,
    Grade,
    Holiday,
    Policy,
)
from app.models.employee import (
    Employee,
    EmployeeBankDetail,
    EmployeeDocument,
    EmployeeEducation,
    EmployeeExperience,
    EmployeeFamilyDetail,
    EmployeeJobDetail,
    EmployeePersonalDetail,
    EmployeeProfileUpdateRequest,
    EmployeeSalaryDetail,
    EmployeeStatutoryDetail,
    EmployeeTimeline,
)
from app.models.permission import Permission, RolePermission
from app.models.role import RefreshToken, Role, UserTenantAccess
from app.models.tenant import Company, Tenant
from app.models.user import User
from app.models.attendance import (
    AttendanceDailySummary,
    AttendanceLog,
    AttendancePolicy,
    AttendanceRegularization,
    BiometricDevice,
    FieldVisit,
)
from app.models.reports import CustomReport
from app.models.tenant_setting import TenantSetting
from app.models.shift import EmployeeShiftAssignment, Roster, Shift, ShiftSwapRequest
from app.models.leave import (
    CompOffRequest,
    LeaveBalance,
    LeavePolicy,
    LeaveRequest,
    LeaveTransaction,
    LeaveType,
)
from app.models.payroll import (
    EmployeeSalaryStructure,
    FullAndFinalSettlement,
    InvestmentProof,
    PayrollDeduction,
    PayrollEarning,
    PayrollEmployee,
    PayrollRun,
    Payslip,
    SalaryComponent,
    SalaryStructure,
    StatutorySetting,
    TaxDeclaration,
)
from app.models.recruitment import (
    Candidate,
    CandidateDocument,
    CandidateStageHistory,
    Interview,
    InterviewFeedback,
    JobOpening,
    JobBoardConnection,
    JobBoardPosting,
    OfferLetter,
    Referral,
)
from app.models.onboarding import NewJoinerDocument, OnboardingChecklist, OnboardingTask, ProbationReview
from app.models.performance import (
    Appraisal,
    Feedback360,
    Goal,
    ManagerReview,
    OKR,
    PerformanceImprovementPlan,
    ReviewCycle,
    SelfReview,
)
from app.models.ai_log import AILog
from app.models.documents import (
    CompanyDocument,
    DocumentCategory,
    GeneratedLetter,
    LetterTemplate,
    LibraryEmployeeDocument,
)
from app.models.helpdesk import (
    Ticket,
    TicketAssignment,
    TicketCategory,
    TicketReply,
    TicketSLA,
)
from app.models.expenses import ExpenseAdvance, ExpenseClaim, ExpensePolicy
from app.models.travel import TravelPolicy, TravelRequest
from app.models.assets import Asset, AssetAssignment
from app.models.communication import Announcement, CommunicationLog, CommunicationTemplate
from app.models.exit import ExitClearance, ExitInterview, Resignation
from app.models.timesheets import TimesheetEntry, TimesheetProject
from app.models.training import TrainingCourse, TrainingEnrollment
from app.models.surveys import Survey, SurveyQuestion, SurveyResponse

__all__ = [
    "Tenant",
    "Company",
    "User",
    "Role",
    "Permission",
    "RolePermission",
    "UserTenantAccess",
    "RefreshToken",
    "AuditLog",
    "CompanyProfile",
    "Branch",
    "Department",
    "Designation",
    "Grade",
    "CostCenter",
    "Holiday",
    "Policy",
    "ApprovalWorkflow",
    "ApprovalStep",
    "Employee",
    "EmployeePersonalDetail",
    "EmployeeJobDetail",
    "EmployeeBankDetail",
    "EmployeeFamilyDetail",
    "EmployeeEducation",
    "EmployeeExperience",
    "EmployeeDocument",
    "EmployeeSalaryDetail",
    "EmployeeStatutoryDetail",
    "EmployeeTimeline",
    "EmployeeProfileUpdateRequest",
    "AttendancePolicy",
    "BiometricDevice",
    "AttendanceLog",
    "AttendanceDailySummary",
    "AttendanceRegularization",
    "FieldVisit",
    "CustomReport",
    "TenantSetting",
    "Shift",
    "EmployeeShiftAssignment",
    "Roster",
    "ShiftSwapRequest",
    "LeaveType",
    "LeavePolicy",
    "LeaveBalance",
    "LeaveRequest",
    "LeaveTransaction",
    "CompOffRequest",
    "SalaryComponent",
    "SalaryStructure",
    "EmployeeSalaryStructure",
    "PayrollRun",
    "PayrollEmployee",
    "PayrollEarning",
    "PayrollDeduction",
    "Payslip",
    "TaxDeclaration",
    "InvestmentProof",
    "StatutorySetting",
    "FullAndFinalSettlement",
    "JobOpening",
    "JobBoardConnection",
    "JobBoardPosting",
    "Candidate",
    "CandidateDocument",
    "CandidateStageHistory",
    "Interview",
    "InterviewFeedback",
    "OfferLetter",
    "Referral",
    "OnboardingChecklist",
    "OnboardingTask",
    "NewJoinerDocument",
    "ProbationReview",
    "Goal",
    "OKR",
    "ReviewCycle",
    "SelfReview",
    "ManagerReview",
    "Feedback360",
    "Appraisal",
    "PerformanceImprovementPlan",
    "AILog",
    "DocumentCategory",
    "LibraryEmployeeDocument",
    "CompanyDocument",
    "LetterTemplate",
    "GeneratedLetter",
    "TicketCategory",
    "Ticket",
    "TicketReply",
    "TicketAssignment",
    "TicketSLA",
    "ExpensePolicy",
    "ExpenseClaim",
    "ExpenseAdvance",
    "TravelPolicy",
    "TravelRequest",
    "Asset",
    "AssetAssignment",
    "Announcement",
    "CommunicationTemplate",
    "CommunicationLog",
    "Resignation",
    "ExitClearance",
    "ExitInterview",
    "TimesheetProject",
    "TimesheetEntry",
    "TrainingCourse",
    "TrainingEnrollment",
    "Survey",
    "SurveyQuestion",
    "SurveyResponse",
]
