from __future__ import annotations

from app.core.enums import PermissionAction, PermissionModule, UserRole

# Default permission matrix — mirrors frontend buildDefaultPermissions.ts
ROLE_PERMISSIONS: dict[UserRole, dict[PermissionModule, set[PermissionAction]]] = {
    UserRole.SUPER_ADMIN: {m: set(PermissionAction) for m in PermissionModule},
    UserRole.COMPANY_ADMIN: {m: set(PermissionAction) for m in PermissionModule},
    UserRole.HR_ADMIN: {
        PermissionModule.DASHBOARD: {PermissionAction.VIEW},
        PermissionModule.COMPANY: {PermissionAction.VIEW},
        PermissionModule.EMPLOYEES: {
            PermissionAction.VIEW,
            PermissionAction.CREATE,
            PermissionAction.EDIT,
            PermissionAction.DELETE,
            PermissionAction.EXPORT,
            PermissionAction.MANAGE,
        },
        PermissionModule.ATTENDANCE: {
            PermissionAction.VIEW,
            PermissionAction.CREATE,
            PermissionAction.EDIT,
            PermissionAction.APPROVE,
            PermissionAction.EXPORT,
            PermissionAction.MANAGE,
        },
        PermissionModule.LEAVE: {
            PermissionAction.VIEW,
            PermissionAction.CREATE,
            PermissionAction.EDIT,
            PermissionAction.APPROVE,
            PermissionAction.EXPORT,
            PermissionAction.MANAGE,
        },
        PermissionModule.RECRUITMENT: {
            PermissionAction.VIEW,
            PermissionAction.CREATE,
            PermissionAction.EDIT,
            PermissionAction.APPROVE,
            PermissionAction.EXPORT,
            PermissionAction.MANAGE,
        },
        PermissionModule.ONBOARDING: {
            PermissionAction.VIEW,
            PermissionAction.CREATE,
            PermissionAction.EDIT,
            PermissionAction.MANAGE,
            PermissionAction.APPROVE,
        },
        PermissionModule.PERFORMANCE: {
            PermissionAction.VIEW,
            PermissionAction.CREATE,
            PermissionAction.EDIT,
            PermissionAction.APPROVE,
            PermissionAction.EXPORT,
            PermissionAction.MANAGE,
        },
        PermissionModule.HELPDESK: {
            PermissionAction.VIEW,
            PermissionAction.CREATE,
            PermissionAction.EDIT,
            PermissionAction.APPROVE,
            PermissionAction.MANAGE,
        },
        PermissionModule.DOCUMENTS: {
            PermissionAction.VIEW,
            PermissionAction.CREATE,
            PermissionAction.EDIT,
            PermissionAction.DELETE,
            PermissionAction.EXPORT,
            PermissionAction.MANAGE,
        },
        PermissionModule.PAYROLL: {PermissionAction.VIEW},
        PermissionModule.EXPENSES: {PermissionAction.VIEW},
        PermissionModule.ASSETS: {
            PermissionAction.VIEW,
            PermissionAction.CREATE,
            PermissionAction.EDIT,
            PermissionAction.MANAGE,
            PermissionAction.APPROVE,
        },
        PermissionModule.REPORTS: {PermissionAction.VIEW, PermissionAction.EXPORT},
        PermissionModule.TIMESHEETS: {
            PermissionAction.VIEW,
            PermissionAction.CREATE,
            PermissionAction.EDIT,
            PermissionAction.APPROVE,
            PermissionAction.EXPORT,
            PermissionAction.MANAGE,
        },
        PermissionModule.TRAINING: {
            PermissionAction.VIEW,
            PermissionAction.CREATE,
            PermissionAction.EDIT,
            PermissionAction.MANAGE,
            PermissionAction.EXPORT,
        },
        PermissionModule.SURVEYS: {
            PermissionAction.VIEW,
            PermissionAction.CREATE,
            PermissionAction.EDIT,
            PermissionAction.MANAGE,
            PermissionAction.EXPORT,
        },
        PermissionModule.AI: {PermissionAction.VIEW, PermissionAction.MANAGE},
        PermissionModule.SETTINGS: {PermissionAction.VIEW},
    },
    UserRole.PAYROLL_ADMIN: {
        PermissionModule.DASHBOARD: {PermissionAction.VIEW},
        PermissionModule.EMPLOYEES: {PermissionAction.VIEW, PermissionAction.EXPORT},
        PermissionModule.PAYROLL: set(PermissionAction),
        PermissionModule.REPORTS: {PermissionAction.VIEW, PermissionAction.EXPORT},
        PermissionModule.SETTINGS: {PermissionAction.VIEW},
        PermissionModule.AI: {PermissionAction.VIEW},
    },
    UserRole.MANAGER: {
        PermissionModule.DASHBOARD: {PermissionAction.VIEW},
        PermissionModule.EMPLOYEES: {PermissionAction.VIEW},
        PermissionModule.ATTENDANCE: {PermissionAction.VIEW, PermissionAction.APPROVE},
        PermissionModule.LEAVE: {PermissionAction.VIEW, PermissionAction.CREATE, PermissionAction.APPROVE},
        PermissionModule.TIMESHEETS: {PermissionAction.VIEW, PermissionAction.CREATE, PermissionAction.APPROVE},
        PermissionModule.TRAINING: {PermissionAction.VIEW},
        PermissionModule.SURVEYS: {PermissionAction.VIEW, PermissionAction.CREATE},
        PermissionModule.PERFORMANCE: {
            PermissionAction.VIEW,
            PermissionAction.CREATE,
            PermissionAction.EDIT,
            PermissionAction.APPROVE,
        },
        PermissionModule.EXPENSES: {PermissionAction.VIEW, PermissionAction.APPROVE},
        PermissionModule.HELPDESK: {PermissionAction.VIEW, PermissionAction.CREATE},
        PermissionModule.ONBOARDING: {PermissionAction.VIEW},
        PermissionModule.AI: {PermissionAction.VIEW},
    },
    UserRole.EMPLOYEE: {
        PermissionModule.DASHBOARD: {PermissionAction.VIEW},
        PermissionModule.ATTENDANCE: {PermissionAction.VIEW},
        PermissionModule.TIMESHEETS: {PermissionAction.VIEW, PermissionAction.CREATE},
        PermissionModule.TRAINING: {PermissionAction.VIEW},
        PermissionModule.SURVEYS: {PermissionAction.VIEW, PermissionAction.CREATE},
        PermissionModule.LEAVE: {PermissionAction.VIEW, PermissionAction.CREATE},
        PermissionModule.HELPDESK: {PermissionAction.VIEW, PermissionAction.CREATE},
        PermissionModule.DOCUMENTS: {PermissionAction.VIEW},
        PermissionModule.EXPENSES: {PermissionAction.VIEW, PermissionAction.CREATE},
        PermissionModule.PERFORMANCE: {PermissionAction.VIEW},
        PermissionModule.PAYROLL: {PermissionAction.VIEW},
        PermissionModule.AI: {PermissionAction.VIEW},
    },
    UserRole.RECRUITER: {
        PermissionModule.DASHBOARD: {PermissionAction.VIEW},
        PermissionModule.RECRUITMENT: set(PermissionAction),
        PermissionModule.ONBOARDING: {
            PermissionAction.VIEW,
            PermissionAction.CREATE,
            PermissionAction.EDIT,
            PermissionAction.MANAGE,
            PermissionAction.APPROVE,
        },
        PermissionModule.EMPLOYEES: {PermissionAction.VIEW},
        PermissionModule.AI: {PermissionAction.VIEW},
    },
    UserRole.FINANCE: {
        PermissionModule.DASHBOARD: {PermissionAction.VIEW},
        PermissionModule.EXPENSES: set(PermissionAction),
        PermissionModule.PAYROLL: {PermissionAction.VIEW, PermissionAction.EXPORT},
        PermissionModule.REPORTS: {PermissionAction.VIEW, PermissionAction.EXPORT},
        PermissionModule.AI: {PermissionAction.VIEW},
    },
    UserRole.AUDITOR: {
        module: {PermissionAction.VIEW}
        for module in PermissionModule
        if module not in (PermissionModule.SETTINGS,)
    }
    | {
        PermissionModule.REPORTS: {PermissionAction.VIEW, PermissionAction.EXPORT},
    },
}

DEFAULT_ROLE_DEFINITIONS: list[dict[str, str]] = [
    {"slug": "super_admin", "name": "Super Admin", "description": "Full system access across all tenants and modules"},
    {"slug": "company_admin", "name": "Company Admin", "description": "Full access within the company tenant"},
    {"slug": "hr_admin", "name": "HR Admin", "description": "HR operations, employee lifecycle, and policies"},
    {"slug": "payroll_admin", "name": "Payroll Admin", "description": "Payroll processing, statutory compliance, and salary"},
    {"slug": "manager", "name": "Manager", "description": "Team management, approvals, and performance reviews"},
    {"slug": "employee", "name": "Employee", "description": "Self-service access to own HR data"},
    {"slug": "recruiter", "name": "Recruiter", "description": "Recruitment pipeline and onboarding coordination"},
    {"slug": "finance", "name": "Finance", "description": "Expense approvals, payroll view, and financial reports"},
    {"slug": "auditor", "name": "Auditor", "description": "Read-only access for compliance and audit reviews"},
]
